# Estágio de Build
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Estágio de Servidor NGINX
FROM nginx:alpine
# Copia o build do React para a pasta padrão do NGINX
COPY --from=build /app/dist /usr/share/nginx/html
# Copia a configuração customizada do NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
