/** Gerado por DS-Extractor — ajuste theme.extend conforme necessário */
module.exports = {
  theme: {
    extend: {
      spacing: {
  "dimension-scale-space-0": "0px",
  "dimension-scale-space-1": "5px",
  "dimension-scale-space-2": "8px",
  "dimension-scale-space-3": "8.188px",
  "dimension-scale-space-4": "9px",
  "dimension-scale-space-5": "10px",
  "dimension-scale-space-6": "12px",
  "dimension-scale-space-7": "13px",
  "dimension-scale-space-8": "13.5px",
  "dimension-scale-space-9": "14px",
  "dimension-scale-space-10": "16px",
  "dimension-scale-space-11": "18px",
  "dimension-scale-space-12": "19px",
  "dimension-scale-space-13": "20px",
  "dimension-scale-space-14": "21px",
  "dimension-scale-space-15": "21.375px",
  "dimension-scale-space-16": "23px",
  "dimension-scale-space-17": "24px",
  "dimension-scale-space-18": "24.172px",
  "dimension-scale-space-19": "30px",
  "dimension-scale-space-20": "32px",
  "dimension-scale-space-21": "33.641px",
  "dimension-scale-space-22": "34px",
  "dimension-scale-space-23": "36px",
  "dimension-suggested-space-0": "0px",
  "dimension-suggested-space-1": "4px",
  "dimension-suggested-space-2": "8px",
  "dimension-suggested-space-3": "8px",
  "dimension-suggested-space-4": "8px",
  "dimension-suggested-space-5": "8px",
  "dimension-suggested-space-6": "12px",
  "dimension-suggested-space-7": "12px",
  "dimension-suggested-space-8": "12px",
  "dimension-suggested-space-9": "12px",
  "dimension-suggested-space-10": "16px",
  "dimension-suggested-space-11": "16px",
  "dimension-suggested-space-12": "20px",
  "dimension-suggested-space-13": "20px",
  "dimension-suggested-space-14": "20px",
  "dimension-suggested-space-15": "20px",
  "dimension-suggested-space-16": "24px",
  "dimension-suggested-space-17": "24px",
  "dimension-suggested-space-18": "24px",
  "dimension-suggested-space-19": "28px",
  "dimension-suggested-space-20": "32px",
  "dimension-suggested-space-21": "32px",
  "dimension-suggested-space-22": "32px",
  "dimension-suggested-space-23": "36px"
},
      colors: {
  "color-semantic-c0": "#78797e",
  "color-semantic-c1": "#fffce3",
  "color-semantic-c2": "#000000",
  "color-semantic-c3": "#0000ee",
  "color-semantic-c4": "#1c1b1d",
  "color-semantic-c5": "#e2dedb",
  "color-semantic-c6": "#ffffff",
  "color-semantic-c7": "#808080"
},
    },
  },
};
